from __future__ import annotations

import argparse
import base64
import json
from pathlib import Path

from .io_utils import read_json, read_jsonl


TEMPLATE = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>EvidenceNet connection audit</title>
<style>
:root{--bg:#08111f;--panel:#111c2e;--panel2:#17243a;--line:#30425e;--text:#edf3fb;--muted:#9cabc2;--blue:#4aa8df;--green:#35c38f;--amber:#f0ab32;--red:#f06b6b;--grey:#929cab;--commercial:#e36f2d}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 system-ui,-apple-system,sans-serif}
header{min-height:68px;padding:13px 20px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:18px}h1{font-size:19px;margin:0}header p{margin:2px 0 0;color:var(--muted)}
.tabs{display:flex;gap:8px}.tabs button,.control{border:1px solid var(--line);background:var(--panel2);color:var(--text);padding:7px 11px;border-radius:7px;cursor:pointer}.tabs button.active{border-color:var(--blue);background:#1d3551}
.summary{display:grid;grid-template-columns:repeat(6,minmax(110px,1fr));gap:10px;padding:14px 20px;border-bottom:1px solid var(--line)}.metric{background:var(--panel);border:1px solid var(--line);border-radius:9px;padding:10px}.metric b{display:block;font-size:20px}.metric span{color:var(--muted);font-size:12px}
main{height:calc(100vh - 157px)}.view{display:none;height:100%}.view.active{display:block}#overview{overflow:auto;padding:20px}.figure{max-width:1260px;margin:auto;background:white;border-radius:10px;padding:8px}.figure img{display:block;width:100%;height:auto}.finding-grid{max-width:1260px;margin:16px auto;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.finding{background:var(--panel);border:1px solid var(--line);border-radius:9px;padding:13px}.finding h3{font-size:13px;color:var(--blue);margin:0 0 7px}.finding p{margin:4px 0;color:var(--muted)}
#review{grid-template-columns:minmax(0,1fr) 390px}#review.active{display:grid}.workspace{min-width:0;overflow:auto}.toolbar{position:sticky;top:0;z-index:5;background:#08111fe8;border-bottom:1px solid var(--line);padding:10px 15px;display:flex;flex-wrap:wrap;gap:9px;align-items:center}.toolbar label{color:var(--muted)}select{background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:6px;padding:6px 8px}
#graph{min-width:900px;min-height:630px}.lane{fill:#0d1829;stroke:#22334d}.lane-title{fill:var(--muted);font-size:12px;font-weight:700}.edge{fill:none;stroke-width:2.5;cursor:pointer}.edge.supported{stroke:var(--green)}.edge.relabel{stroke:var(--amber);stroke-dasharray:7 5}.edge.reject{stroke:var(--grey);opacity:.38}.edge.selected{stroke:white;stroke-width:5;opacity:1}.node{fill:#1b3150;stroke:#7f96b5;stroke-width:1.8;cursor:pointer}.node.commercial{fill:#56301d;stroke:var(--commercial)}.node.selected{stroke:white;stroke-width:4}.node-label{fill:var(--text);font-size:10px;pointer-events:none}.edge-label{font-size:9px;pointer-events:none}
aside{border-left:1px solid var(--line);background:var(--panel);padding:17px;overflow:auto}aside h2{font-size:16px;margin:0 0 10px}.empty{color:var(--muted);padding:35px 4px}.badge{display:inline-block;border-radius:12px;padding:3px 8px;margin:2px 4px 2px 0;font-size:11px;background:#263853}.badge.supported{background:#184f40;color:#a8f1d3}.badge.relabel{background:#5b4315;color:#ffe0a0}.badge.reject{background:#3a414c;color:#d4d8de}.badge.commercial{background:#5c301c;color:#ffc39f}.card{background:#0c1626;border:1px solid var(--line);border-radius:8px;padding:11px;margin:10px 0}.card h3{font-size:12px;color:var(--blue);margin:0 0 6px}.source{white-space:pre-wrap;color:#d4deec;max-height:210px;overflow:auto}.meta{color:var(--muted);font-size:12px}.reason{color:#f0d6a5}.audit-table{width:100%;border-collapse:collapse;margin-top:8px}.audit-table td{padding:5px;border-bottom:1px solid var(--line)}.audit-table td:last-child{text-align:right;font-weight:700}
@media(max-width:900px){.summary{grid-template-columns:repeat(2,1fr)}main{height:auto}#review.active{display:block}.workspace{height:650px}aside{border-left:0;border-top:1px solid var(--line);min-height:350px}.finding-grid{grid-template-columns:1fr}}
</style></head><body>
<header><div><h1>EvidenceNet connection audit</h1><p>Structural integrity, visual-link defects, and manual review of every accepted semantic edge</p></div><div class="tabs"><button id="overviewTab" class="active">Paper figure</button><button id="reviewTab">Interactive graph</button></div></header>
<section class="summary" id="summary"></section>
<main><section id="overview" class="view active"><div class="figure"><img src="data:image/svg+xml;base64,__FIGURE__" alt="EvidenceNet publication graph"></div><div class="finding-grid" id="findings"></div></section>
<section id="review" class="view"><div class="workspace"><div class="toolbar"><label>Issue <select id="docFilter"></select></label><label>Status <select id="statusFilter"><option value="all">All</option><option value="supported">Supported</option><option value="relabel">Relabel/reverse</option><option value="reject">Reject</option></select></label><label><input type="checkbox" id="commercialToggle" checked> show commercial edges</label><span id="visibleCount" class="meta"></span></div><svg id="graph"></svg></div><aside id="details"><div class="empty">Select a connection or node to inspect its evidence.</div></aside></section></main>
<script>
const AUDIT=__AUDIT__,REVIEWS=__REVIEWS__;const docs=AUDIT.documents.map(x=>x.doc_id),shortDoc=d=>d.match(/20\d\d/)?.[0]||d;
const summary=document.querySelector('#summary'),T=AUDIT.totals;
summary.innerHTML=[['Evidence nodes',T.evidence_nodes],['Structural edges',T.structural_edges],['Semantic edges reviewed',T.semantic_edges],['Supported',T.semantic_supported],['Relabel / reverse',T.semantic_relabel],['Rejected',T.semantic_rejected]].map(([k,v])=>`<div class="metric"><b>${Number(v).toLocaleString()}</b><span>${k}</span></div>`).join('');
document.querySelector('#findings').innerHTML=`<div class="finding"><h3>Structural reading order</h3><p>All canonical endpoints resolve.</p><p>NEXT/PREVIOUS inverse and consecutive-order checks pass.</p></div><div class="finding"><h3>Visual/export layer</h3><p><b>${T.graph_json_dangling_edges}</b> graph.json edges have missing visual endpoints.</p><p><b>${T.duplicate_visual_rows}</b> duplicate visual rows; <b>${T.visual_nodes_without_caption}</b> visuals lack captions.</p></div><div class="finding"><h3>Semantic layer</h3><p><b>${T.semantic_supported}/${T.semantic_edges}</b> accepted edges survive strict review.</p><p><b>${T.commercial_semantic_edges}</b> edges touch commercial content and should be excluded from scientific semantics.</p></div>`;
const docFilter=document.querySelector('#docFilter');docFilter.innerHTML=docs.map(d=>`<option value="${d}">${shortDoc(d)}</option>`).join('');
function switchView(name){for(const v of document.querySelectorAll('.view'))v.classList.toggle('active',v.id===name);document.querySelector('#overviewTab').classList.toggle('active',name==='overview');document.querySelector('#reviewTab').classList.toggle('active',name==='review');if(name==='review')render()}
document.querySelector('#overviewTab').onclick=()=>switchView('overview');document.querySelector('#reviewTab').onclick=()=>switchView('review');
const svg=document.querySelector('#graph'),NS='http://www.w3.org/2000/svg';function el(name,attrs={}){const x=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))x.setAttribute(k,v);return x}function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML}function compact(id){const m=id.match(/EV_0*(\d+)$/);return m?'EV-'+m[1]:id}function brief(s,n=55){s=(s||'').replace(/\s+/g,' ');return s.length>n?s.slice(0,n-1)+'…':s}
function filtered(){const doc=docFilter.value,status=document.querySelector('#statusFilter').value,commercial=document.querySelector('#commercialToggle').checked;return REVIEWS.filter(r=>r.doc_id===doc&&(status==='all'||r.status===status)&&(commercial||!r.touches_commercial_content))}
function render(){svg.innerHTML='';const rows=filtered(),all=REVIEWS.filter(r=>r.doc_id===docFilter.value),byOrder={};for(const r of all){byOrder[r.source_document_order]={id:r.source,order:r.source_document_order,text:r.source_text,commercial:r.touches_commercial_content&&r.source_text};byOrder[r.target_document_order]={id:r.target,order:r.target_document_order,text:r.target_text,commercial:r.touches_commercial_content&&r.target_text}}const used=new Set(rows.flatMap(r=>[r.source_document_order,r.target_document_order])),nodes=Object.values(byOrder).filter(n=>used.has(n.order)).sort((a,b)=>a.order-b.order);const columns=6,dx=145,dy=120,left=82,top=90,width=Math.max(900,left*2+(Math.min(columns,Math.max(1,nodes.length))-1)*dx),height=Math.max(600,top+Math.ceil(nodes.length/columns)*dy),pos={};svg.setAttribute('width',width);svg.setAttribute('height',height);svg.style.width=width+'px';svg.style.height=height+'px';const defs=el('defs');defs.innerHTML='<marker id="greenArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="#35c38f"/></marker><marker id="amberArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="#f0ab32"/></marker><marker id="greyArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="#929cab"/></marker>';svg.append(defs);svg.append(el('rect',{x:15,y:25,width:width-30,height:height-50,rx:13,class:'lane'}));const title=el('text',{x:34,y:52,class:'lane-title'});title.textContent=shortDoc(docFilter.value)+' semantic pilot · click any edge';svg.append(title);nodes.forEach((n,i)=>pos[n.order]={x:left+(i%columns)*dx,y:top+Math.floor(i/columns)*dy});for(const r of rows){const a=pos[r.source_document_order],b=pos[r.target_document_order],line=el('path',{d:`M${a.x},${a.y} Q${(a.x+b.x)/2},${(a.y+b.y)/2-28} ${b.x},${b.y}`,class:'edge '+r.status,'marker-end':`url(#${r.status==='supported'?'green':r.status==='relabel'?'amber':'grey'}Arrow)`});line.onclick=()=>showEdge(r,line);svg.append(line)}nodes.forEach(n=>{const p=pos[n.order],commercial=rows.some(r=>r.touches_commercial_content&&(r.source===n.id||r.target===n.id)),c=el('circle',{cx:p.x,cy:p.y,r:15,class:'node '+(commercial?'commercial':''),'data-id':n.id});c.onclick=()=>showNode(n,c);svg.append(c);const t=el('text',{x:p.x,y:p.y+31,'text-anchor':'middle',class:'node-label'});t.textContent=compact(n.id);svg.append(t);const q=el('text',{x:p.x,y:p.y+44,'text-anchor':'middle',class:'node-label'});q.textContent='order '+n.order;svg.append(q)});document.querySelector('#visibleCount').textContent=`${rows.length} visible edges · ${nodes.length} nodes`;if(!rows.length){const t=el('text',{x:width/2,y:height/2,'text-anchor':'middle',class:'lane-title'});t.textContent='No connections match these filters.';svg.append(t)}}
function clearSelected(){document.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'))}function showEdge(r,line){clearSelected();line.classList.add('selected');document.querySelectorAll('.node').forEach(n=>{if(n.dataset.id===r.source||n.dataset.id===r.target)n.classList.add('selected')});document.querySelector('#details').innerHTML=`<h2>${esc(r.edge_type)}</h2><span class="badge ${r.status}">${esc(r.status)}</span>${r.touches_commercial_content?'<span class="badge commercial">commercial</span>':''}<div class="card"><h3>Audit decision</h3><div class="reason">${esc(r.reason)}</div><p class="meta">Model confidence ${esc(r.confidence)} · ${r.crosses_current_content_item?'crosses':'within'} current content item</p></div><div class="card"><h3>Source · ${esc(compact(r.source))} · order ${r.source_document_order}</h3><div class="source">${esc(r.source_text)}</div></div><div class="card"><h3>Target · ${esc(compact(r.target))} · order ${r.target_document_order}</h3><div class="source">${esc(r.target_text)}</div></div>`}function showNode(n,c){clearSelected();c.classList.add('selected');document.querySelector('#details').innerHTML=`<h2>${esc(compact(n.id))}</h2><div class="card"><h3>Evidence node · order ${n.order}</h3><div class="source">${esc(n.text)}</div></div>`}
function showDocAudit(){const d=AUDIT.documents.find(x=>x.doc_id===docFilter.value),s=d.structural_integrity,v=d.visual_integrity,m=d.semantic_integrity;document.querySelector('#details').innerHTML=`<h2>${shortDoc(d.doc_id)} connection audit</h2><table class="audit-table"><tr><td>Evidence nodes</td><td>${d.counts.evidence_nodes}</td></tr><tr><td>Structural edges</td><td>${d.counts.structural_edges}</td></tr><tr><td>Canonical dangling edges</td><td>${s.dangling_edges_against_canonical_files}</td></tr><tr><td>Exported dangling edges</td><td>${v.graph_json_dangling_edges}</td></tr><tr><td>Duplicate visual rows</td><td>${v.duplicate_visual_rows}</td></tr><tr><td>Captionless visuals</td><td>${v.visual_nodes_without_caption}</td></tr><tr><td>Semantic edges</td><td>${d.counts.semantic_edges}</td></tr><tr><td>Commercial semantic edges</td><td>${m.commercial_semantic_edges}</td></tr></table>`}
docFilter.onchange=()=>{render();showDocAudit()};document.querySelector('#statusFilter').onchange=render;document.querySelector('#commercialToggle').onchange=render;
</script></body></html>'''


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a self-contained interactive graph-audit HTML")
    parser.add_argument("--audit-dir", default="output/publication_graph_audit")
    parser.add_argument("--output")
    args = parser.parse_args()
    audit_dir = Path(args.audit_dir)
    audit = read_json(audit_dir / "connection_audit.json")
    reviews = read_jsonl(audit_dir / "semantic_edge_review.jsonl")
    figure = base64.b64encode(
        (audit_dir / "evidencenet_publication_graph.svg").read_bytes()).decode("ascii")
    html = TEMPLATE.replace("__FIGURE__", figure)
    html = html.replace("__AUDIT__", json.dumps(audit, ensure_ascii=False).replace("</", "<\\/"))
    html = html.replace("__REVIEWS__", json.dumps(reviews, ensure_ascii=False).replace("</", "<\\/"))
    target = Path(args.output) if args.output else audit_dir / "evidencenet_graph_review.html"
    target.write_text(html, encoding="utf-8")
    print(target)


if __name__ == "__main__":
    main()
