from __future__ import annotations

import argparse
import json
from pathlib import Path

from .io_utils import read_json, read_jsonl


MODELS = ("Qwen3.5-35B-A3B", "Qwen3.6-35B-A3B")


TEMPLATE = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>EvidenceNet relation taxonomy report</title>
<style>
:root{--bg:#07111f;--panel:#0e1b2e;--panel2:#13243a;--line:#29405d;--text:#eef4fc;--muted:#98abc5;--cyan:#4fc3e8;--green:#49d49d;--amber:#ffb454;--red:#ff6f7d;--purple:#a889ff;--blue:#5795ff}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 85% -10%,#173151 0,transparent 32%),var(--bg);color:var(--text);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}
button,select{font:inherit}.top{position:sticky;top:0;z-index:20;background:#07111ff0;backdrop-filter:blur(14px);border-bottom:1px solid var(--line);padding:14px 24px;display:flex;align-items:center;gap:20px}.brand{flex:1}.brand h1{font-size:20px;margin:0;letter-spacing:.1px}.brand p{color:var(--muted);margin:2px 0 0}.tabs{display:flex;gap:7px}.tabs button,.action{border:1px solid var(--line);background:var(--panel2);color:var(--text);padding:8px 12px;border-radius:8px;cursor:pointer}.tabs button.active{background:#173958;border-color:var(--cyan)}
main{max-width:1440px;margin:auto;padding:22px}.view{display:none}.view.active{display:block}.hero{display:grid;grid-template-columns:1.25fr .75fr;gap:16px;margin-bottom:16px}.hero-main,.hero-side,.card{background:linear-gradient(145deg,#102039,#0d192b);border:1px solid var(--line);border-radius:13px}.hero-main{padding:24px;position:relative;overflow:hidden}.hero-main:after{content:"";position:absolute;width:260px;height:260px;border-radius:50%;background:#2d8bc733;right:-80px;top:-110px}.eyebrow{text-transform:uppercase;letter-spacing:1.5px;color:var(--cyan);font-size:11px;font-weight:800}.hero h2{font-size:32px;line-height:1.12;margin:7px 0 8px;max-width:820px}.hero p{color:var(--muted);margin:0;max-width:850px}.hero-side{padding:20px;display:grid;align-content:center}.decision{font-size:20px;font-weight:750;color:var(--green)}.decision-note{color:var(--muted);margin-top:8px}
.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.metric{padding:16px;background:var(--panel);border:1px solid var(--line);border-radius:11px}.metric b{display:block;font-size:26px}.metric span{display:block;color:var(--muted);font-size:12px}.metric em{font-style:normal;color:var(--green);font-size:12px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px}.card{padding:18px}.card h3{margin:0 0 3px;font-size:16px}.sub{color:var(--muted);font-size:12px;margin-bottom:16px}.legend{display:flex;gap:15px;flex-wrap:wrap;color:var(--muted);font-size:12px;margin:7px 0 14px}.swatch{width:10px;height:10px;border-radius:3px;display:inline-block;margin-right:5px}
.model-group{margin:14px 0 20px}.model-title{font-weight:750;margin-bottom:8px}.bar-row{display:grid;grid-template-columns:175px 1fr 52px;gap:9px;align-items:center;margin:8px 0}.bar-label{color:#c8d5e7;font-size:12px}.track{height:16px;border-radius:8px;background:#071221;border:1px solid #223752;overflow:hidden}.fill{height:100%;border-radius:7px}.value{text-align:right;font-variant-numeric:tabular-nums;font-weight:750}
.taxonomy{display:grid;grid-template-columns:1fr 44px 1.25fr;gap:10px;align-items:center}.old,.new{display:grid;gap:7px}.pill{padding:8px 10px;background:#0a1728;border:1px solid var(--line);border-radius:8px}.pill small{float:right;color:var(--muted)}.arrow{text-align:center;color:var(--cyan);font-size:26px}.merge{border-left:4px solid var(--green)}.special{border-left:4px solid var(--purple)}
.select-row{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:14px}select{background:#0b182a;color:var(--text);border:1px solid var(--line);padding:7px 9px;border-radius:7px}.class-row{display:grid;grid-template-columns:145px 1fr 58px;gap:10px;align-items:center;margin:12px 0}.class-name b{display:block}.class-name span{color:var(--muted);font-size:11px}.f1-track{height:19px;background:#071221;border:1px solid #223752;border-radius:7px;overflow:hidden}.f1{height:100%;background:linear-gradient(90deg,var(--blue),var(--cyan))}.zero .f1{background:var(--red)}
.matrix{width:100%;border-collapse:separate;border-spacing:4px;text-align:center}.matrix th{font-size:10px;color:var(--muted);font-weight:600;padding:5px}.matrix td{height:46px;border:1px solid #29405d;border-radius:6px;font-size:15px;font-weight:800}.matrix .rowlab{text-align:right;background:none!important;border:0;font-size:10px;color:var(--muted);font-weight:600}.matrix-note{display:flex;justify-content:space-between;color:var(--muted);font-size:11px;margin-top:8px}
.stack{height:28px;display:flex;overflow:hidden;border:1px solid var(--line);border-radius:8px;margin:14px 0 10px}.stack span{display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:800;min-width:0}.finding-list{display:grid;gap:8px}.finding{display:grid;grid-template-columns:13px 1fr;gap:8px;color:#cbd7e8}.finding i{width:9px;height:9px;border-radius:50%;margin-top:6px}
.method{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.step{background:#0a1728;border:1px solid var(--line);border-radius:9px;padding:12px;position:relative}.step b{display:block;color:var(--cyan);margin-bottom:3px}.step span{color:var(--muted);font-size:12px}
.audit-layout{display:grid;grid-template-columns:minmax(560px,.95fr) minmax(420px,1.05fr);gap:16px;height:calc(100vh - 122px)}.audit-list,.detail{background:var(--panel);border:1px solid var(--line);border-radius:12px;overflow:auto}.controls{position:sticky;top:0;background:#0e1b2ef2;backdrop-filter:blur(8px);padding:12px;border-bottom:1px solid var(--line);display:flex;gap:8px;z-index:3}.pair-row{padding:11px 13px;border-bottom:1px solid #203651;cursor:pointer;display:grid;grid-template-columns:78px 1fr 92px;gap:9px;align-items:center}.pair-row:hover,.pair-row.active{background:#162943}.task{color:var(--muted);font-size:11px}.pair-main b{display:block}.pair-main span{color:var(--muted);font-size:11px}.badge{display:inline-block;border-radius:12px;padding:3px 8px;font-size:10px;font-weight:800;text-align:center}.exact{background:#174b3b;color:#9bf2cf}.type_error{background:#5b411a;color:#ffd99a}.direction_error{background:#5b2630;color:#ffb2ba}.both_error{background:#51233f;color:#ffc1e5}.detail{padding:18px}.detail h2{margin:0 0 4px}.edge-compare{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.edge-card,.evidence{background:#091626;border:1px solid var(--line);border-radius:9px;padding:12px}.edge-card h4,.evidence h4{margin:0 0 8px;color:var(--cyan)}.edge-line{font-weight:750;font-size:15px}.fine{color:var(--muted);font-size:11px;margin-top:5px}.evidence-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.evidence p{white-space:pre-wrap;color:#c8d4e5;max-height:290px;overflow:auto}.empty{color:var(--muted);padding:40px}
.foot{color:var(--muted);font-size:11px;text-align:center;padding:18px}.warn{color:var(--amber)}
@media(max-width:1000px){.hero,.grid2,.audit-layout{grid-template-columns:1fr}.metrics,.method{grid-template-columns:repeat(2,1fr)}.audit-layout{height:auto}.audit-list,.detail{max-height:none}.top{position:static;flex-wrap:wrap}.bar-row{grid-template-columns:130px 1fr 45px}}
@media print{body{background:white;color:#132033}.top{position:static;background:white}.tabs,.action,#audit{display:none!important}.view{display:block!important}.card,.hero-main,.hero-side,.metric{break-inside:avoid;background:white;border-color:#ccd6e2}.sub,.hero p,.decision-note,.metric span,.class-name span,.finding,.foot{color:#556579}.track,.f1-track{background:#e8eef5}.grid2{page-break-inside:avoid}main{max-width:none}.hero h2{font-size:27px}}
</style></head><body>
<header class="top"><div class="brand"><h1>EvidenceNet · Relation Taxonomy Simplification</h1><p>GW150914 strict benchmark · 28 known-related pairs · type and direction evaluation</p></div><div class="tabs"><button data-view="summary" class="active">Report view</button><button data-view="audit">Pair audit</button></div><button class="action" onclick="window.print()">Print / PDF</button></header>
<main>
<section id="summary" class="view active">
  <div class="hero"><div class="hero-main"><div class="eyebrow">Experiment result</div><h2>Reducing relation granularity improves exact edge construction</h2><p>The best hierarchical coarse run raises exact type + direction accuracy from 50.0% to 67.9%, while preserving 85.2% direction accuracy.</p></div><div class="hero-side"><div class="eyebrow">Recommendation</div><div class="decision">Use Qwen3.6 coarse prompt for the main graph</div><div class="decision-note">Keep the original six-way label as optional metadata. Treat CONDITIONS and CONTRASTS as sparse attributes until more examples are annotated.</div></div></div>
  <div class="metrics" id="metrics"></div>
  <div class="grid2"><div class="card"><h3>Exact type + direction accuracy</h3><div class="sub">Same 28 blind pairs; higher is better</div><div class="legend"><span><i class="swatch" style="background:var(--purple)"></i>Original six-way</span><span><i class="swatch" style="background:var(--amber)"></i>Post-hoc collapse</span><span><i class="swatch" style="background:var(--green)"></i>Coarse prompt</span></div><div id="methodBars"></div></div>
  <div class="card"><h3>Taxonomy mapping</h3><div class="sub">Three functional families with contrast as a special branch</div><div class="taxonomy"><div class="old"><div class="pill">ELABORATES <small>18</small></div><div class="pill">EXPLAINS <small>3</small></div><div class="pill">SUPPORTS <small>4</small></div><div class="pill">QUALIFIES <small>1</small></div><div class="pill">DEPENDS_ON <small>1</small></div><div class="pill">CONTRASTS_WITH <small>1</small></div></div><div class="arrow">→</div><div class="new"><div class="pill merge">EXPANDS <small>21</small></div><div class="pill merge">SUPPORTS <small>4</small></div><div class="pill merge">CONDITIONS <small>2</small></div><div class="pill special">CONTRASTS_WITH <small>1</small></div></div></div></div></div>
  <div class="grid2"><div class="card"><div class="select-row"><div><h3>Per-relation F1</h3><div class="sub" style="margin:0">Coarse-prompt result</div></div><select id="classModel"></select></div><div id="classBars"></div></div>
  <div class="card"><div class="select-row"><div><h3>Confusion matrix</h3><div class="sub" style="margin:0">Rows: reference · columns: prediction</div></div><select id="matrixModel"></select></div><div id="matrix"></div></div></div>
  <div class="grid2"><div class="card"><h3>Best-model error composition</h3><div class="sub">Qwen3.6-35B-A3B · hierarchical coarse prompt</div><div class="stack"><span style="width:67.857%;background:var(--green)">19 exact</span><span style="width:7.143%;background:var(--red)">2 dir.</span><span style="width:14.286%;background:var(--amber)">4 E→S</span><span style="width:7.143%;background:#8b658f">2 cond.</span><span style="width:3.571%;background:var(--purple)"></span></div><div class="legend"><span><i class="swatch" style="background:var(--green)"></i>19 exact</span><span><i class="swatch" style="background:var(--red)"></i>2 direction errors</span><span><i class="swatch" style="background:var(--amber)"></i>4 EXPANDS→SUPPORTS</span><span><i class="swatch" style="background:#8b658f"></i>2 missed CONDITIONS</span><span><i class="swatch" style="background:var(--purple)"></i>1 missed contrast</span></div></div>
  <div class="card"><h3>What the result means</h3><div class="sub">Accuracy alone is misleading because 21/28 references are EXPANDS</div><div class="finding-list"><div class="finding"><i style="background:var(--green)"></i><span>The coarse prompt improves Qwen3.6 exact accuracy by <b>+17.9 percentage points</b>.</span></div><div class="finding"><i style="background:var(--cyan)"></i><span>On the two main families, type accuracy is <b>21/25 = 84%</b>.</span></div><div class="finding"><i style="background:var(--amber)"></i><span>Always-EXPANDS reaches 75% type accuracy but only <b>25% exact accuracy</b> because it cannot orient edges.</span></div><div class="finding"><i style="background:var(--red)"></i><span>Neither model recognizes the 2 CONDITIONS or the single CONTRASTS_WITH reference.</span></div></div></div></div>
  <div class="card"><h3>Controlled evaluation protocol</h3><div class="sub">The experiment isolates relation typing from candidate generation</div><div class="method"><div class="step"><b>1 · Fixed positives</b><span>28 strict/high-confidence pairs; every pair is known to be related.</span></div><div class="step"><b>2 · Label blind</b><span>Models see only Evidence text and metadata, never GT labels or rationale.</span></div><div class="step"><b>3 · Coarse hierarchy</b><span>Contrast first; otherwise EXPANDS, SUPPORTS, or CONDITIONS.</span></div><div class="step"><b>4 · Offline scoring</b><span>Type, direction, exact accuracy, Macro-F1, and confusion matrix.</span></div></div></div>
  <div class="foot">Qwen3.5-397B-A17B was unavailable and is not included. Exact = terminal relation and direction both correct. CONTRASTS_WITH is symmetric.</div>
</section>
<section id="audit" class="view"><div class="audit-layout"><div class="audit-list"><div class="controls"><select id="auditModel"></select><select id="auditStatus"><option value="all">All outcomes</option><option value="exact">Exact</option><option value="type_error">Type error</option><option value="direction_error">Direction error</option><option value="both_error">Type + direction error</option></select><span id="auditCount" class="sub" style="margin:auto 0 auto auto"></span></div><div id="pairs"></div></div><div id="detail" class="detail"><div class="empty">Select a pair to inspect its reference, prediction, direction, and Evidence text.</div></div></div></section>
</main>
<script>
const DATA=__DATA__;const COLORS={fine:'#a889ff',posthoc:'#ffb454',coarse:'#49d49d'},LABELS=['EXPANDS','SUPPORTS','CONDITIONS','CONTRASTS_WITH'];
const $=s=>document.querySelector(s),pct=v=>(100*v).toFixed(1)+'%',shortId=id=>{const m=(id||'').match(/EV_0*(\d+)$/);return m?'EV-'+m[1]:id},esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view));if(b.dataset.view==='audit')renderAudit()});
const best=DATA.models['Qwen3.6-35B-A3B'].coarse,base=best.always_expands_baseline;
$('#metrics').innerHTML=[['67.9%','Best exact accuracy','+17.9 pp vs six-way'],['21 / 28','Coarse type correct','75.0%'],['23 / 27','Direction correct','85.2%'],['21 / 25','Main-family type correct','84.0%']].map(([a,b,c])=>`<div class="metric"><b>${a}</b><span>${b}</span><em>${c}</em></div>`).join('');
function renderMethodBars(){const methods=[['fine','Original six-way'],['posthoc','Post-hoc collapse'],['coarse','Coarse prompt']];$('#methodBars').innerHTML=Object.entries(DATA.models).map(([name,m])=>`<div class="model-group"><div class="model-title">${name}</div>${methods.map(([k,l])=>{const v=m[k].exact_type_and_direction_accuracy;return`<div class="bar-row"><div class="bar-label">${l}</div><div class="track"><div class="fill" style="width:${100*v}%;background:${COLORS[k]}"></div></div><div class="value">${pct(v)}</div></div>`}).join('')}</div>`).join('')}renderMethodBars();
for(const id of ['classModel','matrixModel','auditModel'])$("#"+id).innerHTML=Object.keys(DATA.models).map(m=>`<option>${m}</option>`).join('');$('#classModel').value=$('#matrixModel').value=$('#auditModel').value='Qwen3.6-35B-A3B';
function renderClasses(){const d=DATA.models[$('#classModel').value].coarse;$('#classBars').innerHTML=LABELS.map(l=>{const r=d.per_relation[l];return`<div class="class-row ${r.f1===0?'zero':''}"><div class="class-name"><b>${l}</b><span>${r.support} reference · ${r.predicted} predicted</span></div><div class="f1-track"><div class="f1" style="width:${100*r.f1}%"></div></div><div class="value">${r.f1.toFixed(3)}</div></div>`}).join('')}$('#classModel').onchange=renderClasses;renderClasses();
function renderMatrix(){const d=DATA.models[$('#matrixModel').value].coarse,m=d.confusion_matrix;let h='<table class="matrix"><tr><th></th>'+LABELS.map(l=>`<th>${l.replace('_WITH','')}</th>`).join('')+'</tr>';for(const g of LABELS){const max=Math.max(...LABELS.map(p=>m[g][p]),1);h+=`<tr><td class="rowlab">${g.replace('_WITH','')}</td>`+LABELS.map(p=>{const v=m[g][p],a=.08+.72*v/max,c=g===p?'73,212,157':'255,111,125';return`<td style="background:rgba(${c},${a})" title="${g} → ${p}: ${v}">${v}</td>`}).join('')+'</tr>'}h+='</table><div class="matrix-note"><span>green diagonal = correct</span><span>red off-diagonal = confusion</span></div>';$('#matrix').innerHTML=h}$('#matrixModel').onchange=renderMatrix;renderMatrix();
function status(r){if(r.exact_type_and_direction)return'exact';if(!r.relation_correct&&r.direction_correct===false)return'both_error';if(!r.relation_correct)return'type_error';return'direction_error'}function statusLabel(s){return({exact:'EXACT',type_error:'TYPE ERROR',direction_error:'DIRECTION',both_error:'TYPE + DIR.'})[s]}
function renderAudit(){const model=$('#auditModel').value,filter=$('#auditStatus').value,rows=DATA.models[model].diagnostics.filter(r=>filter==='all'||status(r)===filter);$('#auditCount').textContent=`${rows.length} / 28 pairs`;$('#pairs').innerHTML=rows.map(r=>{const s=status(r);return`<div class="pair-row" data-task="${r.task_id}"><div><div class="task">${r.task_id}</div><b>${shortId(r.gold_source)} ↔ ${shortId(r.gold_target)}</b></div><div class="pair-main"><b>${r.gold_coarse_relation} → ${r.predicted_relation}</b><span>${shortId(r.predicted_source)} → ${shortId(r.predicted_target)}</span></div><span class="badge ${s}">${statusLabel(s)}</span></div>`}).join('');document.querySelectorAll('.pair-row').forEach(row=>row.onclick=()=>showPair(model,row.dataset.task,row))}
function showPair(model,taskId,row){document.querySelectorAll('.pair-row').forEach(x=>x.classList.toggle('active',x===row));const r=DATA.models[model].diagnostics.find(x=>x.task_id===taskId),t=DATA.tasks[taskId],s=status(r),goldDir=r.gold_directed?`${shortId(r.gold_source)} → ${shortId(r.gold_target)}`:'symmetric',predDir=`${shortId(r.predicted_source)} → ${shortId(r.predicted_target)}`;$('#detail').innerHTML=`<span class="badge ${s}">${statusLabel(s)}</span><h2>${r.task_id} · ${shortId(t.evidence_a.node_id)} / ${shortId(t.evidence_b.node_id)}</h2><div class="sub">${model} · confidence ${Number(r.confidence??0).toFixed(2)}</div><div class="edge-compare"><div class="edge-card"><h4>Reference</h4><div class="edge-line">${r.gold_coarse_relation}</div><div>${goldDir}</div><div class="fine">Original fine label: ${r.gold_fine_relation}</div></div><div class="edge-card"><h4>Prediction</h4><div class="edge-line">${r.predicted_relation}</div><div>${predDir}</div><div class="fine">Type ${r.relation_correct?'correct':'wrong'} · direction ${r.direction_correct===null?'symmetric':r.direction_correct?'correct':'wrong'}</div></div></div><div class="evidence-grid">${['evidence_a','evidence_b'].map(k=>{const e=t[k];return`<div class="evidence"><h4>${k==='evidence_a'?'Evidence A':'Evidence B'} · ${shortId(e.node_id)}</h4><div class="fine">${esc((e.section_path||[]).join(' / ')||'Unsectioned')} · ${esc(e.evidence_type)} · ${esc(e.discourse_role)}</div><p>${esc(e.text)}</p></div>`}).join('')}</div>`}
$('#auditModel').onchange=renderAudit;$('#auditStatus').onchange=renderAudit;renderAudit();
</script></body></html>'''


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a self-contained coarse relation experiment report")
    parser.add_argument("--output-root", default="output")
    parser.add_argument("--target", default="output/coarse_relation_typing/relation_taxonomy_report.html")
    args = parser.parse_args()
    root = Path(args.output_root)
    tasks = read_jsonl(root / "strict_relation_typing/shared/blind_tasks.jsonl")
    data = {"tasks": {row["task_id"]: row for row in tasks}, "models": {}}
    for model in MODELS:
        fine_root = root / "strict_relation_typing" / model / "gw150914_detection"
        coarse_root = root / "coarse_relation_typing" / model / "gw150914_detection"
        data["models"][model] = {
            "fine": read_json(fine_root / "evaluation.json"),
            "posthoc": read_json(coarse_root / "posthoc_coarse_evaluation.json"),
            "coarse": read_json(coarse_root / "coarse_evaluation.json"),
            "diagnostics": read_jsonl(coarse_root / "coarse_diagnostics.jsonl"),
        }
    payload = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    target = Path(args.target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(TEMPLATE.replace("__DATA__", payload), encoding="utf-8")
    print(target)


if __name__ == "__main__":
    main()
